version: '3.4'
services:
  post_db:
    container_name: post_db-${TAG}
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      logging:
    restart: on-failure

  ui:
    container_name: ui-${TAG}
    image: ${HUSERNAME}/ui:${TAG}
    ports:
      - 9292:9292/tcp
    networks:
      logging:
      front_net:
        aliases:
          - ui
    environment:
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      COMMENT_SERVICE_HOST: ${COMMENT_SERVICE_HOST}
      COMMENT_SERVICE_PORT: ${COMMENT_SERVICE_PORT}
    command: puma
    restart: on-failure
    depends_on:
      - post
      - comment
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    container_name: post-${TAG}
    image: ${HUSERNAME}/post:${TAG}
    networks:
      logging:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
    environment:
      POST_DATABASE_HOST: ${POST_DATABASE_HOST}
      POST_DATABASE: ${POST_DATABASE}
    entrypoint:
      - python3
      - post_app.py
    restart: on-failure
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    container_name: comment-${TAG}
    image: ${HUSERNAME}/comment:${TAG}
    networks:
      logging:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
    environment:
      COMMENT_DATABASE_HOST: ${COMMENT_DATABASE_HOST}
      COMMENT_DATABASE: ${COMMENT_DATABASE}
    command: puma
    restart: on-failure
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.comment

volumes:
  post_db:

networks:
  front_net:
    external: true
  back_net:
    external: true
  logging:
    external: true

