version: '3.4'
services:
  post_db:
    container_name: post_db-${TAG}
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    restart: on-failure
    logging:
      driver: gelf
      options:
        gelf-address: ${ELK_URI}

  ui:
    container_name: ui-${TAG}
    build: ./ui
    image: ${HUSERNAME}/ui:${TAG}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
    environment:
      POST_SERVICE_HOST: ${POST_SERVICE_HOST}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      COMMENT_SERVICE_HOST: ${COMMENT_SERVICE_HOST}
      COMMENT_SERVICE_PORT: ${COMMENT_SERVICE_PORT}
    command: puma
    restart: on-failure
    depends_on:
      - post
      - comment
    logging:
      driver: gelf
      options:
        gelf-address: ${ELK_URI}

  post:
    container_name: post-${TAG}
    build: ./post-py
    image: ${HUSERNAME}/post:${TAG}
    networks:
      front_net:
        aliases:
          - post
      back_net:
    environment:
      POST_DATABASE_HOST: ${POST_DATABASE_HOST}
      POST_DATABASE: ${POST_DATABASE}
    entrypoint:
      - python3
      - post_app.py
    restart: on-failure
    depends_on:
      - post_db
    logging:
      driver: gelf
      options:
        gelf-address: ${ELK_URI}


  comment:
    container_name: comment-${TAG}
    build: ./comment
    image: ${HUSERNAME}/comment:${TAG}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
    environment:
      COMMENT_DATABASE_HOST: ${COMMENT_DATABASE_HOST}
      COMMENT_DATABASE: ${COMMENT_DATABASE}
    command: puma
    restart: on-failure
    depends_on:
      - post_db
    logging:
      driver: gelf
      options:
        gelf-address: ${ELK_URI}


volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 10.0.2.0/24
